# Generated by Django 2.2.7 on 2020-09-12 14:27

from django.db import migrations
import teachers.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=teachers.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=teachers.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
